WebApplication3/Controllers/ApplicationTypeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Rocky_Utility;
using Rocky_DataAccess;
using Rocky_Models;
using Rocky_Models.ViewModels;

namespace WebApplication3.Controllers
{
    [Authorize(Roles =WC.AdminRole)]
    public class ApplicationTypeController : Controller
    {
        private readonly AppDBContext _db;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public ApplicationTypeController(AppDBContext db, IWebHostEnvironment webHostEnvironment)
        {
            _db = db;
            _webHostEnvironment = webHostEnvironment;
        }  
        public IActionResult Index()
        {
            IEnumerable<ApplicationType> list = _db.ApplicationType;
            return View(list);
        }
        public IActionResult Upsert(int? id)
        {
            if (id != null)
            {
                var obj = _db.ApplicationType.Find(id);

                if (obj == null)
                    return NotFound();

                return View(obj);
            }
            return View(new ApplicationType());
        }

        [HttpPost,ActionName("Upsert")]
        [ValidateAntiForgeryToken]
        public IActionResult UpsertPost(ApplicationType obj)
        {
                var files = HttpContext.Request.Form.Files;
                string webRootPath = _webHostEnvironment.WebRootPath;
                string upload = webRootPath + WC.ImagePath;

                if (obj.Id == 0)
                {
                    string filename = Guid.NewGuid().ToString();
                    string extension = Path.GetExtension(files[0].FileName);

                    using (var filestream = new FileStream(Path.Combine(upload, filename + extension), FileMode.Create))
                    {
                        files[0].CopyTo(filestream);
                    }
                    obj.Image = filename + extension;
                    _db.ApplicationType.Add(obj);
                }
                else
                {
                    var objFromDb = _db.ApplicationType.AsNoTracking().FirstOrDefault(i => i.Id == obj.Id);

                    if(files.Count > 0)
                    {
                        string fileName = Guid.NewGuid().ToString();
                        string extension = Path.GetExtension(files[0].FileName);

                        var oldFile = Path.Combine(upload, objFromDb.Image);
                        if (System.IO.File.Exists(oldFile))
                        {
                            System.IO.File.Delete(oldFile);
                        }

                        using (var filestream = new FileStream(Path.Combine(upload, fileName + extension), FileMode.Create))
                        {
                            files[0].CopyTo(filestream);
                        }
                        obj.Image = fileName + extension;
                    }
                    else
                    {
                        obj.Image = objFromDb.Image;
                    }
                    _db.ApplicationType.Update(obj);
                }
                _db.SaveChanges();
                return RedirectToAction("Index");           
        }
        public IActionResult Delete()
        {
            return View();
        }
    }
}

WebApplication3/Controllers/CardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Security.Claims;
using System.Text;
using Rocky_DataAccess;
using Rocky_Models;
using Rocky_Models.ViewModels;
using Rocky_Utility;
using Rocky_DataAccess.Repository.IRepository;

namespace WebApplication3.Controllers
{
    [Authorize]
    public class CardController : Controller
    {
        private readonly IProductRepository _prodRepo;
        private readonly IApplicationUserRepository _userRepo;
        private readonly IInquiryDetailRepository _inqDRepo;
        private readonly IInquiryHeaderRepository _inqHRepo;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IEmailSender _emailSender;

        [BindProperty]
        public ProductUserVM ProductUserVM { get; set; }

        public CardController(IWebHostEnvironment webHostEnvironment, IEmailSender emailSender, IInquiryDetailRepository inqDRepo,
                              IInquiryHeaderRepository inqHRepo,IApplicationUserRepository userRepo, IProductRepository prodRepo)
        {
            _userRepo= userRepo;
            _prodRepo= prodRepo;
            _webHostEnvironment = webHostEnvironment;
            _emailSender = emailSender;
            _inqDRepo = inqDRepo;
            _inqHRepo = inqHRepo;
        }

        public IActionResult Index()
        {
            List<ShoppingCard> shoppingCards= new List<ShoppingCard>();
            if(HttpContext.Session.Get<List<ShoppingCard>>(WC.SessionCart) != null &&
               HttpContext.Session.Get<List<ShoppingCard>>(WC.SessionCart).Count() > 0 )
            {
                // сессия существуют
                shoppingCards = HttpContext.Session.Get<List<ShoppingCard>>(WC.SessionCart);
            }

            List<int> prodInCart = shoppingCards.Select(u => u.ProductId).ToList();
            List<Product> products = _prodRepo.GetAll(u => prodInCart.Contains(u.Id)).ToList();

            return View(products);
        }

        public IActionResult Remove(int id)
        {
            List<ShoppingCard> shoppingCards = new List<ShoppingCard>();
            if (HttpContext.Session.Get<List<ShoppingCard>>(WC.SessionCart) != null &&
               HttpContext.Session.Get<List<ShoppingCard>>(WC.SessionCart).Count() > 0)
            {
                // сессия существуют
                shoppingCards = HttpContext.Session.Get<List<ShoppingCard>>(WC.SessionCart);
            }

            shoppingCards.Remove(shoppingCards.FirstOrDefault(u => u.ProductId == id));
            HttpContext.Session.Set(WC.SessionCart, shoppingCards);

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Index")]
        public IActionResult IndexPost()
        {        
            return RedirectToAction(nameof(Summary));
        }

        public IActionResult Summary()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier); // получение имени пользователя, если он зашел в систему
            //var userId = User.FindFirstValue(ClaimTypes.Name); // второй способ

            List<ShoppingCard> shoppingCards = new List<ShoppingCard>();
            if (HttpContext.Session.Get<List<ShoppingCard>>(WC.SessionCart) != null &&
               HttpContext.Session.Get<List<ShoppingCard>>(WC.SessionCart).Count() > 0)
            {
                // сессия существуют
                shoppingCards = HttpContext.Session.Get<List<ShoppingCard>>(WC.SessionCart);
            }

            List<int> prodInCart = shoppingCards.Select(u => u.ProductId).ToList();
            List<Product> products = _prodRepo.GetAll(u => prodInCart.Contains(u.Id)).ToList();

            ProductUserVM = new ProductUserVM()
            {
                ApplicationUser = _userRepo.FirstOrDefault(u => u.Id == claim.Value),
                ProductList = products
            };

            return View(ProductUserVM);        
        }
      
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Summary")]
        public async Task<IActionResult> SummaryPost(ProductUserVM ProductUserVM)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            var PathToTemplate = _webHostEnvironment.WebRootPath + Path.DirectorySeparatorChar.ToString() // путь к htmlbody для сообщения
                + "templates" + Path.DirectorySeparatorChar.ToString() + "EmailMessageBody.html";

            var subject = "New Inquiry";
            string HtmlBody;
            using(StreamReader sr = System.IO.File.OpenText(PathToTemplate)) // открывем файл и записываем в переменную
            {
                HtmlBody = sr.ReadToEnd();
            }

            StringBuilder productListSB = new StringBuilder();
            foreach (var prod in ProductUserVM.ProductList) // перебираем все продукты
            {
                productListSB.Append($"- Name: {prod.Name} <span style='font-size:14px;'> (ID: {prod.Id}) </span> <br />");
            }

            string messageBody = string.Format(HtmlBody, ProductUserVM.ApplicationUser.FullName, // записываем в html документ
                                                         ProductUserVM.ApplicationUser.Email,
                                                         ProductUserVM.ApplicationUser.PhoneNumber,
                                                         productListSB.ToString());

            await _emailSender.SendEmailAsync("vgerman2004@mail.ru", subject, messageBody);

            InquiryHeader inquiryHeader = new InquiryHeader
            {
                ApplicationUserId = claim.Value,
                FullName = ProductUserVM.ApplicationUser.FullName,
                Email = ProductUserVM.ApplicationUser.Email,
                PhoneNumber = ProductUserVM.ApplicationUser.PhoneNumber,
                InquiryDate = DateTime.Now
            };

            _inqHRepo.Add(inquiryHeader );
            _inqHRepo.Save();

            foreach (var prod in ProductUserVM.ProductList) // перебираем все продукты
            {
                InquiryDetail inquiryDetail = new InquiryDetail
                {
                    InquiryHeaderId = inquiryHeader.Id,
                    ProductId = prod.Id
                };
                _inqDRepo.Add(inquiryDetail);
            }
            _inqDRepo.Save(); 

            return RedirectToAction(nameof(InquiryConfirmation));
        }

        public IActionResult InquiryConfirmation(ProductUserVM ProductUserVM)
        {
            HttpContext.Session.Clear();
            return View();
        }
    }
}

WebApplication3/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Rocky_Utility;
using System.Data;
using Rocky_DataAccess;
using Rocky_Models;
using Rocky_DataAccess.Repository.IRepository;

namespace WebApplication3.Controllers
{
    [Authorize(Roles = WC.AdminRole)]
    public class CategoryController : Controller
    {
        private readonly ICategoryRepository _catRepo;

        public CategoryController(ICategoryRepository catRepo)
        {
            _catRepo= catRepo;
        }

        public IActionResult Index()
        {
            IEnumerable<Category> list = _catRepo.GetAll();
            return View(list);
        }

        public IActionResult Create()
        {          
            return View();
        }

        public IActionResult Delete(int id)
        {
            var obj = _catRepo.Find(id);
            return View(obj);
        }

        public IActionResult Edit(int? id)
        {
            if(id == null || id == 0)
                return NotFound();

            var obj = _catRepo.Find(id.GetValueOrDefault());

            if(obj == null)
                return NotFound();

            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            if (id == null || id == 0)
                return NotFound();

            var obj = _catRepo.Find(id.GetValueOrDefault());

            _catRepo.Remove(obj);
            _catRepo.Save();
            return RedirectToAction("Index");
        }

        [HttpPost] 
        [ValidateAntiForgeryToken] //токен защиты от взлома
        public IActionResult Create(Category obj)
        {
            if (ModelState.IsValid) // реализация валидации на стороне сервера
            {
                _catRepo.Add(obj);
                _catRepo.Save();
                TempData[WC.Success] = "cruto";
                return RedirectToAction("Index"); // перенапрвление на страницу с категориями
            }
            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken] //токен защиты от взлома
        public IActionResult Edit(Category obj)
        {
            if (ModelState.IsValid) // реализация валидации на стороне сервера
            {
                _catRepo.Update(obj);
                _catRepo.Save();
                return RedirectToAction("Index"); // перенапрвление на страницу с категориями
            }
            return View(obj);
        }       
    }
}

WebApplication3/Controllers/InquiryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Rocky_DataAccess.Repository.IRepository;
using Rocky_Models;
using Rocky_Models.ViewModels;
using Rocky_Utility;
using System.Linq.Expressions;

namespace WebApplication3.Controllers
{
    [Authorize(Roles = WC.AdminRole)]
    public class InquiryController : Controller
    {
        private readonly IInquiryHeaderRepository _inqHRepo;
        private readonly IInquiryDetailRepository _inqDRepo;

        [BindProperty]
        public InquiryVM InquiryVM { get; set; }

        public InquiryController(IInquiryHeaderRepository inqHRepo, IInquiryDetailRepository inqDRepo)
        {
            _inqHRepo = inqHRepo;
            _inqDRepo = inqDRepo;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Details(int id)
        {
            InquiryVM inquiryVM = new InquiryVM()
            {
                InquiryHeader = _inqHRepo.FirstOrDefault(u => u.Id == id),
                InquiryDetail = _inqDRepo.GetAll(u => u.Id == id, includeProperties: "Product")
            };
            return View(inquiryVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DetailsPost(int id)
        {
            List<ShoppingCard> shoppingCardList = new List<ShoppingCard>();
            InquiryVM.InquiryDetail = _inqDRepo.GetAll(u => u.InquiryHeaderId == InquiryVM.InquiryHeader.Id);

            foreach (var detail in InquiryVM.InquiryDetail)
            {
                ShoppingCard shoppingCard = new ShoppingCard
                {
                    ProductId = detail.ProductId,
                };
                shoppingCardList.Add(shoppingCard);
            }
            HttpContext.Session.Clear();
            HttpContext.Session.Set(WC.SessionCart,shoppingCardList);
            HttpContext.Session.Set(WC.SessionInquiryId, InquiryVM.InquiryHeader.Id); // если равно 0 то значит в сессии не использовалась работы с INQUIRY

            InquiryVM inquiryVM = new InquiryVM()
            {
                InquiryHeader = _inqHRepo.FirstOrDefault(u => u.Id == id),
                InquiryDetail = _inqDRepo.GetAll(u => u.Id == id, includeProperties: "Product")
            };
            return View(inquiryVM);
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            InquiryHeader inquiryHeader = _inqHRepo.FirstOrDefault(u =>u.Id == InquiryVM.InquiryHeader.Id);
            IEnumerable<InquiryDetail> inquiryDetails = _inqDRepo.GetAll(u => u.InquiryHeaderId == InquiryVM.InquiryHeader.Id);

            _inqDRepo.RemoveRange(inquiryDetails);
            _inqHRepo.Remove(inquiryHeader);
            _inqDRepo.Save();

            return RedirectToAction(nameof(Index));
        }
        #region API Calls
        [HttpGet]
        public IActionResult GetInquiryList()
        {
            return Json(new { data = _inqHRepo.GetAll() });
        }
        #endregion
    }
}

WebApplication3/Views/Shared/_IndividualProductCard.cshtml
@using Rocky_Utility;
 @model Rocky_Models.Product
      
 <div class="col-lg-4 col-md-6 pb-4 filter @Model.Category.CategoryName.Replace(' ','_')">
            <!-- Card-->
            <div class="card bg-white rounded shadow-sm" style="border:1px solid #222">
                <div class="card-body px-3 pt-3 pb-1 row">
                    <div class="col-7"><label class="float-left">@Model.Name</label></div>
                    <div class="col-5"><label class="float-right"><span class="text-info h5">@string.Format("{0:с0}",@Model.Price)</span></label> </div>
                </div>
                <img class="card-img-top img-fluid d-block mx-auto mb-3" src="@WC.ImagePath@Model.Image" alt="Card image cap">
                <div class="card-body p-1 px-3 row">
                    <div class="col-6">
                        <span class="badge p-2 border w-100" style="background-color:black">@Model.Category.CategoryName</span>
                    </div>
                <div class="col-6 border-0">
                    <span class="badge p-2 border w-100" style="background-color:black">@Model.ApplicationType.Name</span>
                </div>
                <div class="col-12 p-1">
                    <a asp-action="Details" asp-route-id="@Model.Id" class="btn btn-dark form-control btn-sm p-2" style="height:40px">View Details</a>
                </div>
                </div>
            </div>
 </div>

WebApplication3/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@using Rocky_Utility

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication3.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/fontawesom/css/all.css" />
    <link rel="stylesheet" href="~/css/toastr.css" />
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.2/css/jquery.dataTables.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication3</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">


                    <ul class="navbar-nav flex-grow-1">
                        @if (User.IsInRole(WC.AdminRole))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Content Management</a>
                                <ul class="dropdown-menu">
                                    <li><a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a></li>
                                    <li><a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a></li>
                                    <li><a class="nav-link text-dark" asp-area="" asp-controller="ApplicationType" asp-action="Index">ApplicationType</a></li>
                                    <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Create Admin User</a>
                                </ul>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Order/Inquiry Management</a>
                                <ul class="dropdown-menu">
                                    <a class="nav-link text-dark" asp-action="Index" asp-controller="Inquiry">Inquiry</a>
                                </ul>
                            </li>
                        }
                        <li>
                            @if (HttpContextAccessor.HttpContext.Session.Get<List<ShoppingCard>>(WC.SessionCart) != null) // проверка существования сессии для карты товаров
                            {
                                <a asp-action="Index" asp-controller="Card" class="nav-link">
                                    @{
                                        var count = (HttpContextAccessor.HttpContext.Session.Get<List<ShoppingCard>>(WC.SessionCart)).Count(); // количество товаров
                                    }
                                    <i class="fas fa-shopping-cart"></i> &nbsp; (@count)
                                </a>
                            }
                            else
                            {
                                <a href="#" class="nav-link">
                                    <i class="fas fa-shopping-cart"></i> &nbsp; (0)
                                </a>
                            }
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notifications" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebApplication3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.2/js/jquery.dataTables.js"></script>
    <script src="~/js/toastr.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApplication3/Views/Shared/_Notifications.cshtml
@using Rocky_Utility

@if(TempData[WC.Success] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/toastr.min.js"></script>
    <script type="text/javascript">toastr.success('@TempData[WC.Success]')</script>
}